// Code generated by protoc-gen-go.
// source: job.proto
// DO NOT EDIT!

/*
Package jobs is a generated protocol buffer package.

It is generated from these files:
	job.proto

It has these top-level messages:
	Job
	Notification
*/
package furrow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	RequestID string      `protobuf:"bytes,1,opt,name=RequestID" json:"RequestID,omitempty"`
	Image     string      `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	Cmd       []string    `protobuf:"bytes,3,rep,name=Cmd" json:"Cmd,omitempty"`
	Env       []string    `protobuf:"bytes,4,rep,name=Env" json:"Env,omitempty"`
	Notify    string      `protobuf:"bytes,5,opt,name=Notify" json:"Notify,omitempty"`
	Volumes   *Job_Volume `protobuf:"bytes,7,opt,name=volumes" json:"volumes,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Job) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Job) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Job) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Job) GetNotify() string {
	if m != nil {
		return m.Notify
	}
	return ""
}

func (m *Job) GetVolumes() *Job_Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Job_Volume struct {
	In  string `protobuf:"bytes,1,opt,name=In" json:"In,omitempty"`
	Out string `protobuf:"bytes,2,opt,name=Out" json:"Out,omitempty"`
}

func (m *Job_Volume) Reset()                    { *m = Job_Volume{} }
func (m *Job_Volume) String() string            { return proto.CompactTextString(m) }
func (*Job_Volume) ProtoMessage()               {}
func (*Job_Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Job_Volume) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

func (m *Job_Volume) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

type Notification struct {
	ID   uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Notification) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Notification) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "jobs.Job")
	proto.RegisterType((*Job_Volume)(nil), "jobs.Job.Volume")
	proto.RegisterType((*Notification)(nil), "jobs.Notification")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x3f, 0xdd, 0x92, 0x51, 0xa4, 0x0c, 0x22, 0x41, 0x3c, 0x2c, 0x3d, 0x2d, 0x3d,
	0xe4, 0x50, 0x3f, 0x82, 0xdb, 0x43, 0x7a, 0x50, 0xc8, 0xc1, 0x7b, 0xa2, 0x51, 0xb6, 0xb8, 0x19,
	0x75, 0xb3, 0x0b, 0x7e, 0x48, 0xbf, 0x93, 0xe4, 0x8f, 0xf4, 0xf6, 0xe6, 0x37, 0x79, 0xbc, 0x97,
	0x01, 0x76, 0x22, 0x23, 0x3e, 0xbf, 0xc9, 0x13, 0xd6, 0x27, 0x32, 0xd3, 0xf6, 0xb7, 0x80, 0xea,
	0x48, 0x06, 0xef, 0x80, 0x29, 0xfb, 0x35, 0xdb, 0xc9, 0xcb, 0x9e, 0x17, 0x6d, 0xd1, 0x31, 0x75,
	0x06, 0x78, 0x0d, 0x2b, 0x39, 0xea, 0x77, 0xcb, 0xcb, 0xb8, 0x49, 0x03, 0x6e, 0xa0, 0x7a, 0x18,
	0x5f, 0x79, 0xd5, 0x56, 0x1d, 0x53, 0x41, 0x06, 0x72, 0x70, 0x0b, 0xaf, 0x13, 0x39, 0xb8, 0x05,
	0x6f, 0xa0, 0x79, 0x24, 0x3f, 0xbc, 0xfd, 0xf0, 0x55, 0xb4, 0xe6, 0x09, 0x77, 0xb0, 0x5e, 0xe8,
	0x63, 0x1e, 0xed, 0xc4, 0xd7, 0x6d, 0xd1, 0x5d, 0xec, 0x37, 0x22, 0xf4, 0x11, 0x47, 0x32, 0xe2,
	0x39, 0x2e, 0xd4, 0xff, 0x83, 0xdb, 0x1d, 0x34, 0x09, 0xe1, 0x15, 0x94, 0xd2, 0xe5, 0x7a, 0xa5,
	0x74, 0x21, 0xef, 0x69, 0xf6, 0xb9, 0x55, 0x90, 0xdb, 0x3d, 0x5c, 0xc6, 0x84, 0xe1, 0x45, 0xfb,
	0x81, 0x5c, 0x74, 0xa4, 0x0f, 0xd5, 0xaa, 0x94, 0x3d, 0x22, 0xd4, 0xbd, 0xf6, 0x3a, 0x5b, 0xa2,
	0x36, 0x4d, 0x3c, 0xc8, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x2f, 0xb1, 0xd1, 0x1d,
	0x01, 0x00, 0x00,
}
